"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Card } from "@/components/ui/Card";
import { useTelemetry } from "@/hooks/useTelemetry";
import { useAdaptiveUIState } from "@/hooks/useAdaptiveUIState";
import { useSimplificationMetrics } from "@/hooks/useSimplificationMetrics";
import { ResponsiveContainer, ScatterChart, Scatter, CartesianGrid, XAxis, YAxis, Tooltip, Legend, BarChart, Bar, PieChart, Pie, Cell } from "recharts";
import { listIndustryCases, listPrimitives } from "@/controllers/insightController";
import type { Opportunity } from "@/domain/knowledge";

type Insight = {
  id: string;
  title: string;
  impact: "Cost" | "Risk" | "Efficiency";
  summary: string;
};

const MOCK_INSIGHTS: Insight[] = [
  { id: "insight-1", title: "Reduce middleware overlap", impact: "Cost", summary: "Consolidate Boomi + MuleSoft connectors into a single integration lane to cut run-rate and support effort." },
  { id: "insight-2", title: "Stabilize PIM dependencies", impact: "Risk", summary: "High coupling between PIM and storefront indicates fragility during catalog updates; introduce async buffering." },
  { id: "insight-3", title: "Modernize reporting stack", impact: "Efficiency", summary: "Adopt a single BI path (Snowflake + Looker) to reduce redundant dashboards and improve data trust." },
];

const COLORS = ["#2563eb", "#9333ea", "#0ea5e9", "#1e293b", "#334155", "#64748b"];

type TelemetryMetrics = {
  ok: boolean;
  navigation: Array<{ scene: string; views: number; avg_ms: number; total_ms: number }>;
  conversation: { sent: number; received: number; depth_ratio: number };
  decisions: { total: number; by_scene: Record<string, number> };
  aiTrust: { signals: number; prompts: number; index: number };
  pulse: { total: number; by_step: Record<string, number> };
};

type PanelKey = "activity" | "engagement" | "actions" | "reports";

const PANEL_META: Record<PanelKey, { label: string; description: string }> = {
  activity: {
    label: "User Activity",
    description: "Navigation flow clarity, dwell time, and most visited scenes.",
  },
  engagement: {
    label: "User Engagement",
    description: "Conversational depth and AI trust signals captured during this session.",
  },
  actions: {
    label: "User Actions",
    description: "Transformation decisions and pulse transitions generated by the agent.",
  },
  reports: {
    label: "Org Intelligence Reports",
    description: "Organizational alignment, stakeholder sentiment, and readiness summaries.",
  },
};

const REPORT_OPTIONS: Array<{ id: ReportApiType; label: string }> = [
  { id: "org_alignment", label: "Alignment Index" },
  { id: "org_readiness", label: "Readiness Index" },
];

type ReportApiType = "org_alignment" | "org_readiness";

type OrgReportPayload = {
  type: ReportApiType;
  metadata: { title: string; generated: string; organization: string };
  summary: string;
  stakeholders?: Array<{ name: string; alignment: number; influence: number; bias: string; notes?: string }>;
  decisions?: Array<{ id: string; title: string; alignment: number; roi: number; tcc: number; supporters: string[]; resisters?: string[]; timeline?: string }>;
  sentimentSummary?: string;
  recommendations: string[];
  metrics?: { consensus_score?: number; polarization_index?: number; dominant_strategy?: string };
  categories?: Array<{ name: string; readiness: number; risk: string; notes: string }>;
  readinessScore?: number;
  confidence?: number;
  stage?: string;
  deltaHistory?: Array<{ date: string; score: number }>;
  markdown: string;
};

const formatPercent = (value: number) => `${(value * 100).toFixed(0)}%`;

export function InsightsScene({ projectId }: { projectId: string }) {
  const telemetry = useTelemetry("insights", { projectId });
  const { snapshot, setMetrics } = useSimplificationMetrics("insights");
  const router = useRouter();
  const searchParams = useSearchParams();
  const urlFocus = (searchParams?.get("focus") as PanelKey) ?? "activity";
  const {
    showContextBar,
    contextMessage,
    setContextMessage,
    assistVisible,
    assistMessage,
    setAssistMessage,
    setAssistVisible,
    ctaEnabled,
    setCtaEnabled,
    ctaLabel,
    setCtaLabel,
    progress,
    setProgress,
  } = useAdaptiveUIState("insights", {
    initialContext: "Review insights grouped by impact. Export once you’ve opened one.",
    initialCTA: "Export insights",
    initialProgress: 0.25,
  });

  const [insights] = useState<Insight[]>(MOCK_INSIGHTS);
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [exported, setExported] = useState(false);
  const idleTimer = useRef<number | null>(null);
  const [metricSummary, setMetricSummary] = useState<TelemetryMetrics | null>(null);
  const [metricsError, setMetricsError] = useState<string | null>(null);
  const [activePanel, setActivePanel] = useState<PanelKey>(urlFocus);
  const [reportType, setReportType] = useState<ReportApiType>("org_alignment");
  const [reportDataMap, setReportDataMap] = useState<Record<ReportApiType, OrgReportPayload | null>>({
    org_alignment: null,
    org_readiness: null,
  });
  const [reportError, setReportError] = useState<string | null>(null);
  const [reportLoading, setReportLoading] = useState(false);
  const activeReportData = reportDataMap[reportType];

  useEffect(() => {
    setActivePanel(urlFocus);
  }, [urlFocus]);

  const handlePanelChange = (panel: PanelKey) => {
    if (panel === activePanel) return;
    const params = new URLSearchParams(searchParams?.toString() ?? "");
    params.set("scene", "insights");
    params.set("focus", panel);
    router.replace(`/project/${projectId}/experience?${params.toString()}`, { scroll: false });
    setActivePanel(panel);
  };

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/insights", { cache: "no-store" });
        if (!res.ok) throw new Error("Failed");
        const data = await res.json();
        if (!cancelled) setOpportunities(data.opportunities ?? []);
      } catch {
        if (!cancelled) {
          const { getMockInsights } = await import("@/controllers/insightController");
          setOpportunities(getMockInsights());
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const fetchReport = useCallback(
    async (type: ReportApiType) => {
      setReportLoading(true);
      setReportError(null);
      try {
        const res = await fetch(`/api/intelligence/report?type=${type}`, { cache: "no-store" });
        if (!res.ok) throw new Error(`Failed to load report (${res.status})`);
        const json = (await res.json()) as OrgReportPayload;
        setReportDataMap((prev) => ({ ...prev, [type]: json }));
        telemetry.log("intelligence_report_loaded", { projectId, type });
      } catch (error: any) {
        setReportError(error?.message ?? "Unable to load report");
      } finally {
        setReportLoading(false);
      }
    },
    [projectId, telemetry],
  );

  useEffect(() => {
    if (activePanel !== "reports") return;
    if (reportDataMap[reportType] || reportLoading) return;
    void fetchReport(reportType);
  }, [activePanel, fetchReport, reportDataMap, reportType, reportLoading]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/telemetry/metrics", { cache: "no-store" });
        if (!res.ok) throw new Error("Failed to load telemetry metrics");
        const json = (await res.json()) as TelemetryMetrics;
        if (!cancelled) setMetricSummary(json);
      } catch (err: any) {
        if (!cancelled) setMetricsError(err?.message ?? "Failed to load metrics");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const simplificationScore = useMemo(() => {
    const sss = snapshot?.metrics?.SSS ?? 2.0;
    return Math.min(1, Math.max(0, sss / 5));
  }, [snapshot]);

  const simplificationLabel = simplificationScore >= 0.8 ? "Clean insights" : simplificationScore >= 0.5 ? "Mostly aligned" : "Needs focus";
  const simplificationTone =
    simplificationScore >= 0.8 ? "bg-emerald-50 text-emerald-800 border-emerald-200" : simplificationScore >= 0.5 ? "bg-amber-50 text-amber-800 border-amber-200" : "bg-rose-50 text-rose-700 border-rose-200";

  useEffect(() => {
    telemetry.log("insights_view", { projectId }, simplificationScore);
  }, [projectId, telemetry, simplificationScore]);

  useEffect(() => {
    const openedCount = expanded.size;
    const nextProgress = openedCount > 0 ? 0.75 : 0.4;
    setProgress(nextProgress);
    setCtaEnabled(openedCount > 0);
    setContextMessage(openedCount > 0 ? "Insights reviewed — export a summary to capture this run." : "Open at least one insight to enable export.");
    setCtaLabel(openedCount > 0 ? "Export insights" : "Open an insight to export");
  }, [expanded.size, setContextMessage, setCtaEnabled, setCtaLabel, setProgress]);

  useEffect(() => {
    if (idleTimer.current) {
      window.clearTimeout(idleTimer.current);
    }
    idleTimer.current = window.setTimeout(() => {
      setAssistVisible(true);
      setAssistMessage("Need a quick summary? Open an insight and export to share.");
      telemetry.log("insights_idle", { idle_ms: 45000 }, simplificationScore);
    }, 45000);
    return () => {
      if (idleTimer.current) {
        window.clearTimeout(idleTimer.current);
      }
    };
  }, [expanded, setAssistMessage, setAssistVisible, telemetry, simplificationScore]);

  const toggleInsight = (insight: Insight) => {
    setAssistVisible(false);
    setAssistMessage(null);
    setExported(false);
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(insight.id)) {
        next.delete(insight.id);
      } else {
        next.add(insight.id);
      }
      return next;
    });
    telemetry.log("insight_toggle", { id: insight.id, impact: insight.impact, expanded: !expanded.has(insight.id) }, simplificationScore);
  };

  const handleExport = () => {
    setExported(true);
    telemetry.log("insight_export_complete", { projectId, opened: Array.from(expanded) }, simplificationScore);
    telemetry.log("decision_taken", { projectId, scene: "insights", decision: "export_insights", opened: expanded.size });
  };

  const handleDownloadReport = () => {
    if (!activeReportData?.markdown) return;
    const blob = new Blob([activeReportData.markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = reportType === "org_alignment" ? "org_alignment_report.md" : "org_readiness_report.md";
    link.click();
    URL.revokeObjectURL(url);
    telemetry.log("intelligence_report_downloaded", { projectId, type: reportType });
  };

  const handleRefreshReport = () => {
    setReportDataMap((prev) => ({ ...prev, [reportType]: null }));
    void fetchReport(reportType);
  };

  const handleClarityChange = (value: number) => {
    setMetrics({ DC: value });
  };

  const primitives = listPrimitives();
  const cases = listIndustryCases();

  const scatterData = opportunities.map((opp) => ({
    x: opp.impactEffort.effort,
    y: opp.impactEffort.impact,
    z: opp.aiOpportunityIndex,
    name: opp.title,
  }));

  const indexByQuadrant = ["quick_win", "strategic_investment", "self_service", "deprioritize"].map((quadrant) => ({
    quadrant,
    count: opportunities.filter((o) => o.impactEffort.quadrant === quadrant).length,
  }));

  const frictionCounts = opportunities.reduce<Record<string, number>>((acc, opp) => {
    opp.frictionZones.forEach((zone) => {
      acc[zone] = (acc[zone] ?? 0) + 1;
    });
    return acc;
  }, {});

  const frictionData = Object.entries(frictionCounts).map(([name, value]) => ({ name, value }));
  const navigationMetrics = metricSummary?.navigation ?? [];
  const conversationMetrics = metricSummary?.conversation;
  const decisionMetrics = metricSummary?.decisions;
  const aiTrustMetrics = metricSummary?.aiTrust;
  const pulseMetrics = metricSummary?.pulse;

  return (
    <div className="space-y-4">
      {showContextBar && (
        <Card className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-[0.65rem] uppercase tracking-[0.22em] text-slate-500">Context</p>
            <p className="text-xs text-slate-700">{contextMessage || "Adaptive guidance will respond as you interact."}</p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <div className="h-2 w-36 rounded-full bg-slate-100">
              <div className="h-2 rounded-full bg-slate-900 transition-all" style={{ width: `${Math.round(progress * 100)}%` }} />
            </div>
            <span className="text-[0.75rem] font-semibold text-slate-800">{Math.round(progress * 100)}%</span>
            <button
              type="button"
              disabled={!ctaEnabled}
              onClick={handleExport}
              className={`rounded-full px-4 py-1.5 text-[0.75rem] font-semibold ${ctaEnabled ? "bg-slate-900 text-white hover:bg-slate-800" : "bg-slate-200 text-slate-500 cursor-not-allowed"}`}
            >
              {ctaLabel}
            </button>
          </div>
        </Card>
      )}

      <Card className="space-y-3 border border-slate-200">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Intelligence Focus</p>
            <p className="text-sm font-semibold text-slate-900">{PANEL_META[activePanel].label}</p>
          </div>
          <div className="flex flex-wrap gap-2">
            {(Object.keys(PANEL_META) as PanelKey[]).map((panel) => (
              <button
                key={panel}
                type="button"
                onClick={() => handlePanelChange(panel)}
                className={`rounded-full px-3 py-1 text-xs font-semibold ${
                  activePanel === panel ? "bg-slate-900 text-white shadow" : "border border-slate-200 text-slate-700 hover:border-slate-900"
                }`}
              >
                {PANEL_META[panel].label}
              </button>
            ))}
          </div>
        </div>
        <p className="text-xs text-slate-600">{PANEL_META[activePanel].description}</p>
      </Card>

      {activePanel === "reports" && (
        <OrgIntelligenceReportPanel
          data={activeReportData}
          loading={reportLoading}
          error={reportError}
          onRefresh={handleRefreshReport}
          onDownload={handleDownloadReport}
        />
      )}

      {activePanel === "activity" && (
        <div className="grid gap-3 md:grid-cols-2">
          <Card className="space-y-2 border border-slate-200">
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Top Scenes</p>
            {navigationMetrics.length ? (
              <ul className="space-y-1 text-sm text-slate-700">
                {navigationMetrics.slice(0, 4).map((entry) => (
                  <li key={entry.scene} className="flex items-center justify-between">
                    <span>{entry.scene}</span>
                    <span className="text-xs text-slate-500">{Math.round(entry.avg_ms / 1000)}s avg dwell</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-slate-500">Navigation telemetry not captured yet.</p>
            )}
          </Card>
          <Card className="space-y-2 border border-slate-200">
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Flow Clarity</p>
            {navigationMetrics.length ? (
              <>
                <p className="text-sm text-slate-800">
                  {navigationMetrics.length} scenes ·{" "}
                  {Math.round(navigationMetrics.reduce((sum, entry) => sum + entry.total_ms, 0) / 1000)}s total dwell
                </p>
                <p className="text-xs text-slate-500">`scene_view_time` + `nav_section_toggled`</p>
              </>
            ) : (
              <p className="text-xs text-slate-500">Awaiting scene_view_time telemetry.</p>
            )}
            {metricsError ? <p className="text-xs text-rose-600">{metricsError}</p> : null}
          </Card>
        </div>
      )}

      {activePanel === "engagement" && (
        <div className="grid gap-3 md:grid-cols-2">
          <Card className="space-y-2 border border-slate-200">
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Conversation Depth</p>
            {conversationMetrics ? (
              <>
                <p className="text-sm text-slate-800">
                  Sent {conversationMetrics.sent} · Received {conversationMetrics.received}
                </p>
                <p className="text-xs text-slate-500">Depth ratio {(conversationMetrics.depth_ratio * 100).toFixed(0)}%</p>
              </>
            ) : (
              <p className="text-xs text-slate-500">No agent_message telemetry yet.</p>
            )}
          </Card>
          <Card className="space-y-2 border border-slate-200">
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">AI Trust Index</p>
            {aiTrustMetrics ? (
              <>
                <p className="text-3xl font-semibold text-slate-900">{Math.round(aiTrustMetrics.index * 100)}%</p>
                <p className="text-xs text-slate-500">
                  {aiTrustMetrics.signals} signals · {aiTrustMetrics.prompts} prompts
                </p>
              </>
            ) : (
              <p className="text-xs text-slate-500">No ai_trust_signal telemetry yet.</p>
            )}
          </Card>
        </div>
      )}

      {activePanel === "actions" && (
        <div className="grid gap-3 md:grid-cols-2">
          <Card className="space-y-2 border border-slate-200">
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Decision Log</p>
            {decisionMetrics ? (
              <>
                <p className="text-3xl font-semibold text-slate-900">{decisionMetrics.total}</p>
                <ul className="text-xs text-slate-600">
                  {Object.entries(decisionMetrics.by_scene).map(([scene, count]) => (
                    <li key={scene}>
                      {scene}: {count}
                    </li>
                  ))}
                </ul>
              </>
            ) : (
              <p className="text-xs text-slate-500">No decision_taken events yet.</p>
            )}
          </Card>
          <Card className="space-y-2 border border-slate-200">
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Pulse Transitions</p>
            {pulseMetrics ? (
              <>
                <p className="text-3xl font-semibold text-slate-900">{pulseMetrics.total}</p>
                <ul className="text-xs text-slate-600">
                  {Object.entries(pulseMetrics.by_step).map(([step, value]) => (
                    <li key={step}>
                      {step}: {value}
                    </li>
                  ))}
                </ul>
              </>
            ) : (
              <p className="text-xs text-slate-500">No pulse_state_change telemetry yet.</p>
            )}
          </Card>
        </div>
      )}

      {assistVisible && assistMessage ? (
        <Card className="border border-slate-200 bg-slate-50 text-xs text-slate-700">{assistMessage}</Card>
      ) : null}

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        <Card className="p-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Navigation clarity</p>
          {metricSummary?.navigation?.length ? (
            <div className="mt-2 space-y-1 text-sm text-slate-700">
              {metricSummary.navigation.slice(0, 3).map((entry) => (
                <p key={entry.scene}>
                  {entry.scene}: <span className="font-semibold">{entry.views}</span> views · avg {entry.avg_ms}ms
                </p>
              ))}
            </div>
          ) : (
            <p className="mt-2 text-sm text-slate-500">{metricsError ?? "Collecting scene views…"}</p>
          )}
        </Card>
        <Card className="p-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Conversational depth</p>
          <p className="mt-2 text-sm text-slate-700">
            Sent <span className="font-semibold">{metricSummary?.conversation?.sent ?? 0}</span> · Received <span className="font-semibold">{metricSummary?.conversation?.received ?? 0}</span>
          </p>
          <p className="text-xs text-slate-500">Depth ratio: {metricSummary?.conversation ? metricSummary.conversation.depth_ratio.toFixed(2) : "0.00"}</p>
        </Card>
        <Card className="p-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Decisions</p>
          <p className="mt-2 text-sm text-slate-700">{metricSummary?.decisions?.total ?? 0} actions captured</p>
          <ul className="mt-1 text-xs text-slate-500">
            {metricSummary?.decisions?.by_scene ? (
              Object.entries(metricSummary.decisions.by_scene)
                .slice(0, 3)
                .map(([scene, count]) => (
                  <li key={scene}>
                    {scene}: {count}
                  </li>
                ))
            ) : (
              <li>No decisions yet</li>
            )}
          </ul>
        </Card>
        <Card className="p-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">AI Trust Index</p>
          <p className="mt-2 text-2xl font-semibold text-slate-900">{Math.round((metricSummary?.aiTrust?.index ?? 0) * 100)}%</p>
          <p className="text-xs text-slate-500">{metricSummary?.aiTrust?.signals ?? 0} trust signals out of {metricSummary?.aiTrust?.prompts ?? 0} prompts.</p>
        </Card>
        <Card className="p-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Pulse changes</p>
          <p className="mt-2 text-sm text-slate-700">{metricSummary?.pulse?.total ?? 0} focus shifts</p>
          <ul className="mt-1 text-xs text-slate-500">
            {metricSummary?.pulse?.by_step ? (
              Object.entries(metricSummary.pulse.by_step)
                .slice(0, 3)
                .map(([step, count]) => (
                  <li key={step}>
                    {step}: {count}
                  </li>
                ))
            ) : (
              <li>No transitions yet</li>
            )}
          </ul>
        </Card>
      </div>

      <div className={`rounded-2xl border px-4 py-3 text-sm ${simplificationTone}`}>
        Simplification score: <span className="font-semibold">{simplificationLabel}</span>
        <input
          type="range"
          min={0}
          max={100}
          className="mt-2 w-full"
          defaultValue={snapshot?.metrics?.DC ?? 42}
          onChange={(event) => handleClarityChange(Number(event.target.value))}
        />
      </div>

      <Card className="p-4">
        <div className="mb-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Impact vs Effort</p>
          <p className="text-sm text-slate-600">Bubble size reflects AI Opportunity Index (higher is better).</p>
        </div>
        <div className="w-full" style={{ minHeight: 320 }}>
          <ResponsiveContainer width="100%" height={320}>
            <ScatterChart margin={{ left: 16, right: 16, top: 8, bottom: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis type="number" dataKey="x" name="Effort" stroke="#94a3b8" domain={[0, 100]} tick={{ fontSize: 11 }} />
              <YAxis type="number" dataKey="y" name="Impact" stroke="#94a3b8" domain={[0, 100]} tick={{ fontSize: 11 }} />
              <Tooltip cursor={{ fill: "rgba(15,23,42,0.04)" }} contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0" }} />
              <Legend />
              <Scatter name="Opportunities" data={scatterData} fill="#2563eb" shape="circle" line />
            </ScatterChart>
          </ResponsiveContainer>
        </div>
      </Card>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="p-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500 mb-2">Opportunities by Quadrant</p>
          <div className="w-full" style={{ minHeight: 240 }}>
            <ResponsiveContainer width="100%" height={240}>
              <BarChart data={indexByQuadrant}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis dataKey="quadrant" stroke="#94a3b8" tick={{ fontSize: 11 }} />
                <YAxis stroke="#94a3b8" />
                <Tooltip cursor={{ fill: "rgba(15,23,42,0.04)" }} contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0" }} />
                <Legend />
                <Bar dataKey="count" fill="#2563eb" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Card>
        <Card className="p-4">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500 mb-2">Friction Zone Distribution</p>
          <div className="w-full" style={{ minHeight: 240 }}>
            <ResponsiveContainer width="100%" height={240}>
              <PieChart>
                <Pie data={frictionData} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="80%" paddingAngle={3}>
                  {frictionData.map((entry, idx) => (
                    <Cell key={entry.name} fill={COLORS[idx % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip cursor={{ fill: "rgba(15,23,42,0.04)" }} contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0" }} />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </Card>
      </div>

      <Card className="p-4">
        <div className="mb-3">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Opportunities</p>
          <p className="text-sm text-slate-600">Sorted by AI Opportunity Index; mock data for now.</p>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead className="text-xs uppercase text-slate-500 bg-slate-50">
              <tr>
                <th className="px-3 py-2 text-left">Title</th>
                <th className="px-3 py-2 text-left">Friction</th>
                <th className="px-3 py-2 text-left">Primitives</th>
                <th className="px-3 py-2 text-left">Impact</th>
                <th className="px-3 py-2 text-left">Effort</th>
                <th className="px-3 py-2 text-left">Readiness</th>
                <th className="px-3 py-2 text-left">AI Index</th>
                <th className="px-3 py-2 text-left">Quadrant</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {opportunities
                .slice()
                .sort((a, b) => b.aiOpportunityIndex - a.aiOpportunityIndex)
                .map((opp) => (
                  <tr key={opp.id} className="hover:bg-slate-50">
                    <td className="px-3 py-2 font-semibold text-slate-900">{opp.title}</td>
                    <td className="px-3 py-2 text-slate-600">{opp.frictionZones.join(", ")}</td>
                    <td className="px-3 py-2 text-slate-600">
                      {opp.primitives.map((p) => primitives.find((item) => item.id === p)?.name ?? p).join(", ")}
                    </td>
                    <td className="px-3 py-2">{opp.impactEffort.impact}</td>
                    <td className="px-3 py-2">{opp.impactEffort.effort}</td>
                    <td className="px-3 py-2">{opp.impactEffort.readiness ?? 0}</td>
                    <td className="px-3 py-2 font-semibold text-slate-900">{opp.aiOpportunityIndex}</td>
                    <td className="px-3 py-2 text-slate-600">{opp.impactEffort.quadrant}</td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </Card>

      <Card className="p-4">
        <p className="text-xs uppercase tracking-[0.3em] text-slate-500 mb-2">Insights</p>
        <div className="space-y-3">
          {insights.map((insight) => (
            <button key={insight.id} type="button" onClick={() => toggleInsight(insight)} className="w-full rounded-2xl border border-slate-200 p-3 text-left hover:border-slate-900">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-sm font-semibold text-slate-900">{insight.title}</p>
                  <p className="text-[11px] uppercase tracking-[0.3em] text-slate-500">{insight.impact}</p>
                </div>
                <span className="text-base text-slate-400">{expanded.has(insight.id) ? "▾" : "▸"}</span>
              </div>
              {expanded.has(insight.id) ? <p className="mt-2 text-sm text-slate-600">{insight.summary}</p> : null}
            </button>
          ))}
        </div>
        {exported && <p className="mt-3 text-xs text-emerald-700">Summary exported with {expanded.size} insights.</p>}
      </Card>

      <Card className="p-4">
        <p className="text-xs uppercase tracking-[0.3em] text-slate-500 mb-2">Industry Cases (Reference)</p>
        <div className="grid gap-3 lg:grid-cols-3">
          {cases.map((item) => (
            <div key={item.id} className="rounded-xl border border-slate-200 p-3">
              <div className="flex items-center justify-between">
                <p className="text-sm font-semibold text-slate-900">{item.challenge}</p>
                <span className="text-[11px] text-slate-500">{item.industry}</span>
              </div>
              <p className="text-xs text-slate-600 mt-1">{item.notes}</p>
              <div className="mt-2 text-xs text-slate-500">Primitives: {item.primitives.join(", ")}</div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}

function OrgIntelligenceReportPanel({
  data,
  loading,
  error,
  onRefresh,
  onDownload,
}: {
  data: OrgReportPayload | null;
  loading: boolean;
  error: string | null;
  onRefresh: () => void;
  onDownload: () => void;
}) {
  return (
    <Card className="space-y-4 border border-slate-200">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Org Alignment Report</p>
          <p className="text-sm font-semibold text-slate-900">{data?.metadata.title ?? "Synthesizing report…"}</p>
          {data ? <p className="text-xs text-slate-500">Generated {new Date(data.metadata.generated).toLocaleString()}</p> : null}
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={onRefresh}
            className="rounded-full border border-slate-200 px-3 py-1 text-xs font-semibold text-slate-700 hover:border-slate-900 disabled:opacity-60"
            disabled={loading}
          >
            {loading ? "Refreshing…" : "Refresh"}
          </button>
          <button
            type="button"
            onClick={onDownload}
            disabled={!data}
            className="rounded-full bg-slate-900 px-3 py-1 text-xs font-semibold text-white disabled:opacity-60"
          >
            Download Markdown
          </button>
        </div>
      </div>
      {loading && <p className="text-xs text-slate-500">Generating report with ALE + EAgent signals…</p>}
      {error && <p className="text-xs text-rose-600">{error}</p>}
      {data && !loading ? (
        <>
          <div className="grid gap-3 md:grid-cols-3">
            <div>
              <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Consensus</p>
              <p className="text-3xl font-semibold text-slate-900">{(data.metrics.consensus_score * 100).toFixed(0)}%</p>
              <p className="text-xs text-slate-500">Strategy: {data.metrics.dominant_strategy}</p>
            </div>
            <div>
              <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Polarization</p>
              <p className="text-3xl font-semibold text-slate-900">{(data.metrics.polarization_index * 100).toFixed(0)}%</p>
              <p className="text-xs text-slate-500">Lower is better</p>
            </div>
            <div>
              <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500">Summary</p>
              <p className="text-xs text-slate-600">{data.summary}</p>
            </div>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            <div>
              <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500 mb-2">Stakeholders</p>
              <div className="max-h-48 overflow-auto rounded-2xl border border-slate-100">
                <table className="w-full text-left text-xs text-slate-600">
                  <thead>
                    <tr className="text-[0.6rem] uppercase tracking-widest text-slate-500">
                      <th className="px-3 py-2">Name</th>
                      <th className="px-3 py-2">Align</th>
                      <th className="px-3 py-2">Influence</th>
                      <th className="px-3 py-2">Bias</th>
                    </tr>
                  </thead>
                  <tbody>
                    {data.stakeholders.map((stakeholder) => (
                      <tr key={stakeholder.name} className="border-t border-slate-100 text-[0.7rem]">
                        <td className="px-3 py-2 text-slate-800">{stakeholder.name}</td>
                        <td className="px-3 py-2">{stakeholder.alignment.toFixed(2)}</td>
                        <td className="px-3 py-2">{stakeholder.influence.toFixed(2)}</td>
                        <td className="px-3 py-2 text-slate-500">{stakeholder.bias}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
            <div>
              <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500 mb-2">Key Decisions</p>
              <ul className="space-y-2 text-xs text-slate-700">
                {data.decisions.map((decision) => (
                  <li key={decision.id} className="rounded-2xl border border-slate-200 p-3">
                    <p className="text-[0.75rem] font-semibold text-slate-900">{decision.title}</p>
                    <p className="text-[0.65rem] text-slate-500">
                      Alignment {decision.alignment.toFixed(2)} · ROI {formatPercent(decision.roi)} · TCC {formatPercent(decision.tcc)}
                    </p>
                    <p className="text-[0.65rem] text-slate-500">{`Support ${decision.supporters.join(", ")}`}</p>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          <div>
            <p className="text-[0.65rem] uppercase tracking-[0.3em] text-slate-500 mb-1">Sentiment + Readiness</p>
            <p className="text-xs text-slate-600">{data.sentimentSummary}</p>
            {data.recommendations.length ? (
              <ul className="mt-2 space-y-1 text-xs text-slate-600">
                {data.recommendations.map((rec, idx) => (
                  <li key={rec}>
                    {idx + 1}. {rec}
                  </li>
                ))}
              </ul>
            ) : null}
          </div>
        </>
      ) : null}
    </Card>
  );
}
