#!/usr/bin/env node

/**
 * Generate Organizational Readiness Index artifacts (Markdown + JSON) plus ROI/TCC correlation notes.
 * Usage: `node scripts/generate_org_readiness_report.js`
 */

const fs = require("fs");
const path = require("path");

const readinessComponents = require("../src/data/org_insights/readiness_components.json");
const readinessProfiles = require("../src/data/org_insights/readiness_profiles.json");
const decisionVelocity = require("../src/data/telemetry/decision_velocity.json");
const sequencerProgress = require("../src/data/sequencer_progress.json");
const learningState = require("../src/data/ale/learning_state.json");
const roiSummary = require("../src/data/roi_tcc_summary.json");

const REPORT_DIR = path.join(process.cwd(), "intelligence", "reports");
const INDEX_MD = path.join(REPORT_DIR, "org_readiness_index.md");
const DELTA_JSON = path.join(REPORT_DIR, "org_readiness_delta.json");
const CORRELATION_MD = path.join(REPORT_DIR, "org_readiness_to_roi.md");

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function formatPercent(value, digits = 0) {
  return `${(Number(value || 0) * 100).toFixed(digits)}%`;
}

function average(values) {
  if (!values.length) return 0;
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function dimensionFor(name = "") {
  const normalized = name.toLowerCase();
  if (normalized.match(/integration|infrastructure|data|platform|architecture/)) return "capability";
  if (normalized.match(/team|governance|agility|ownership|decision/)) return "organizational";
  if (normalized.match(/change|enablement|sentiment|behavior|culture/)) return "behavioral";
  return "capability";
}

function buildIndexMarkdown(payload) {
  const lines = [];
  lines.push("# Organizational Readiness Index – OMS Transformation");
  lines.push(`Generated: ${payload.generated}`);
  lines.push(`Organization: ${payload.organization}`);
  lines.push(
    `Readiness Score: ${formatPercent(payload.readinessScore)} | Confidence: ${formatPercent(payload.confidence)} | Stage: ${payload.stage}`,
  );
  lines.push("", "## Readiness Summary", payload.summary, "");
  lines.push("### Category Breakdown");
  lines.push("| Category | Readiness | Risk | Notes |", "|----------|-----------|------|-------|");
  payload.categories.forEach((category) => {
    lines.push(`| ${category.name} | ${formatPercent(category.readiness)} | ${category.risk} | ${category.notes} |`);
  });
  lines.push("", "### Recommendations");
  payload.recommendations.forEach((rec, idx) => lines.push(`${idx + 1}. ${rec}`));
  if (payload.deltaHistory?.length) {
    lines.push("", "### Readiness Delta", "Date | Score", "-----|------");
    payload.deltaHistory.forEach((entry) => lines.push(`${entry.date} | ${formatPercent(entry.score)}`));
  }
  lines.push("", "---", "Generated by Fuxi Intelligence Engine (ALE + EAgent)");
  return lines.join("\n");
}

function buildCorrelationMarkdown(payload) {
  const lines = [];
  lines.push("# Readiness ↔ ROI/TCC Correlation Summary");
  lines.push(
    `Current ORI ${formatPercent(payload.readinessScore)} (confidence ${formatPercent(payload.confidence)}) at stage ${payload.stage}. Decision velocity index ${payload.decisionVelocity} and FY26 sequencer completion ${formatPercent(payload.progress.fy26)}.`,
  );
  lines.push("", "## ROI / TCC by Phase");
  lines.push("| Phase | ROI | TCC |", "|-------|-----|-----|");
  (roiSummary.phases ?? []).forEach((phase) => {
    lines.push(`| ${phase.label} | ${formatPercent(phase.roi ?? 0)} | ${phase.tcc?.toFixed(1) ?? "0"} |`);
  });
  lines.push("", "## Path Comparison");
  (roiSummary.paths ?? []).forEach((path) => {
    lines.push(
      `- **${path.label}** – ROI ${formatPercent(path.roi ?? 0)}, TCC ${path.tcc?.toFixed(1) ?? "0"}, confidence ${formatPercent(
        path.confidence ?? 0,
      )}. ${path.notes}`,
    );
  });
  lines.push(
    "",
    `With readiness below 0.7, Fuxi favors the ${
      (roiSummary.paths ?? []).sort((a, b) => (b.confidence ?? 0) - (a.confidence ?? 0))[0]?.label ?? "highest confidence"
    } path to preserve execution runway.`,
  );
  lines.push("", "Monitor readiness deltas to unlock Phase 3 ROI acceleration.");
  return lines.join("\n");
}

function main() {
  ensureDir(REPORT_DIR);

  const categories = readinessComponents.categories ?? [];
  const dimensions = { capability: [], organizational: [], behavioral: [] };
  categories.forEach((category) => {
    const dimension = dimensionFor(category.name);
    dimensions[dimension].push(Number(category.readiness ?? 0));
  });
  const dimensionMetrics = {
    capability: average(dimensions.capability.length ? dimensions.capability : categories.map((c) => Number(c.readiness ?? 0))),
    organizational: average(dimensions.organizational.length ? dimensions.organizational : categories.map((c) => Number(c.readiness ?? 0))),
    behavioral: average(dimensions.behavioral.length ? dimensions.behavioral : categories.map((c) => Number(c.readiness ?? 0))),
  };

  const readinessScore = Number(learningState.org_readiness_score ?? average(categories.map((c) => Number(c.readiness ?? 0))));
  const payload = {
    organization: readinessComponents.organization ?? readinessProfiles.organization ?? "Deckers",
    generated: new Date().toISOString(),
    readinessScore,
    confidence: readinessComponents.confidence ?? 0.85,
    stage: readinessComponents.stage ?? readinessProfiles.readiness_stage ?? "In Progress",
    summary:
      readinessProfiles.signals && readinessProfiles.signals.alignment_trend
        ? `Stakeholder alignment trend ${(readinessProfiles.signals.alignment_trend * 100).toFixed(
            0,
          )}% with capability focus on ${((readinessProfiles.capability_focus ?? [])[0] ?? "core platforms").toLowerCase()}. ${
            readinessComponents.recommendations?.[0] ?? ""
          }`
        : "Readiness synthesized from integration, governance, and behavioral telemetry.",
    categories,
    recommendations: readinessComponents.recommendations ?? [],
    deltaHistory: learningState.delta_history ?? [],
    metrics: dimensionMetrics,
    decisionVelocity: decisionVelocity.velocity_index ?? 0,
    progress: {
      fy26: sequencerProgress.phases?.find((p) => p.phase === "FY26")?.complete ?? 0,
      fy27: sequencerProgress.phases?.find((p) => p.phase === "FY27")?.complete ?? 0,
      fy28: sequencerProgress.phases?.find((p) => p.phase === "FY28")?.complete ?? 0,
    },
  };

  const markdown = buildIndexMarkdown(payload);
  fs.writeFileSync(INDEX_MD, `${markdown}\n`);

  const deltaPayload = {
    organization: payload.organization,
    readinessScore: payload.readinessScore,
    confidence: payload.confidence,
    stage: payload.stage,
    delta_history: payload.deltaHistory,
    decision_velocity: payload.decisionVelocity,
    sequencer_progress: payload.progress,
    metrics: payload.metrics,
    categories: payload.categories,
  };
  fs.writeFileSync(DELTA_JSON, `${JSON.stringify(deltaPayload, null, 2)}\n`);

  const correlationMarkdown = buildCorrelationMarkdown(payload);
  fs.writeFileSync(CORRELATION_MD, `${correlationMarkdown}\n`);

  console.log("✅ Generated ORI markdown:", INDEX_MD);
  console.log("✅ Generated ORI delta JSON:", DELTA_JSON);
  console.log("✅ Generated ORI ↔ ROI/TCC correlation:", CORRELATION_MD);
}

main();
